version: '3'

services: 
  jenkins:
    build: ./v.0.2.0
    container_name: jenkins
    restart: always
    ports: 
      - 8080:8080
      - 50000:50000
  # jenkins:
  #   build: ./v.0.1.0
  #   container_name: jenkins
  #   restart: always
  #   ports: 
  #     - 8080:8080
  #     - 50000:50000
networks:
  default: