version: '3'

services: 
  jenkins:
    build: ./v.1.0.0
    image: ismaelalvesdoc/jenkins:1.0.0
    container_name: jenkins
    restart: always
    volumes: 
      - ./jenkins_home_8:/var/jenkins_home
      - ./jenkins_backup_8:/srv/backup
    #  - /var/run/docker.sock:/var/run/docker.sock #linux
    #  - localhost:2375:/var/run/docker.sock #windows
    ports: 
      - 8080:8080
      - 50000:50000
  # jenkins:
  #   build: ./v.0.4.0
  #   container_name: jenkins
  #   restart: always
  #   volumes: 
  #     - ./jenkins_home_4:/var/jenkins_home
  #     - ./jenkins_backup_4:/srv/backup
  #   ports: 
  #     - 8080:8080
  #     - 50000:50000
  # jenkins:
  #   build: ./v.0.3.0
  #   container_name: jenkins
  #   restart: always
  #   volumes: 
  #     - ./jenkins_home_3:/var/jenkins_home
  #     - ./jenkins_backup_3:/srv/backup
  #   ports: 
  #     - 8080:8080
  #     - 50000:50000
  # jenkins:
  #   build: ./v.0.2.0
  #   container_name: jenkins
  #   restart: always
  #   ports: 
  #     - 8080:8080
  #     - 50000:50000
  # jenkins:
  #   build: ./v.0.1.0
  #   container_name: jenkins
  #   restart: always
  #   ports: 
  #     - 8080:8080
  #     - 50000:50000
networks:
  default: